# Generated by Django 6.0.1 on 2026-01-11 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa rasy')),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Imię psa')),
                ('age', models.PositiveIntegerField(verbose_name='Wiek')),
                ('description', models.TextField(verbose_name='Opis')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dogs/', verbose_name='Zdjęcie')),
                ('is_available', models.BooleanField(default=True, verbose_name='Dostępny do adopcji')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoptions.breed', verbose_name='Rasa')),
            ],
        ),
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Wiadomość do schroniska')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Numer telefonu')),
                ('date_applied', models.DateTimeField(auto_now_add=True, verbose_name='Data złożenia')),
                ('status', models.CharField(choices=[('pending', 'Oczekujący'), ('accepted', 'Zaakceptowany'), ('rejected', 'Odrzucony')], default='pending', max_length=10, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoptions.dog', verbose_name='Pies')),
            ],
        ),
    ]
